//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbSystem.EntityDataBase.SqlEntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.MOVIES = new HashSet<MOVy>();
        }
    
        public string userID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userNickName { get; set; }
        public Nullable<System.DateTime> userBirthDate { get; set; }
        public string userGender { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string userPicture { get; set; }
        public string userImdbPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVy> MOVIES { get; set; }
    }
}
